apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: consul-telemetry-collector
  namespace: consul
spec:
  destination:
    name: consul-telemetry-collector
  sources:
  - action: allow
    name: '*'