{
 "title": "Control Plane Logs",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "consul" },
   { "name": "app", "query": "consul" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({app=\"$app\", namespace=\"$namespace\"} | logfmt | __error__=`` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Log Type Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(_TRACE_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[TRACE]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "TRACE"
    },
    {
     "expr": "sum by(_DEBUG_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[DEBUG]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "DEBUG"
    },
    {
     "expr": "sum by(_INFO_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[INFO]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "INFO"
    },
    {
     "expr": "sum by(_ERROR_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[ERROR]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "RPC Server Call Success/Error Ratio",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(errored) (count_over_time({app=\"$app\", namespace=\"$namespace\"} | logfmt | __error__=`` | errored!=\"\" [$__range]))",
     "legendFormat": "Error: {{errored}}"
    }
   ]
  },
  {
   "title": "HTTP Method Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({app=\"$app\", namespace=\"$namespace\"} | logfmt | __error__=`` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Log Type Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by(_TRACE_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[TRACE]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "TRACE"
    },
    {
     "expr": "sum by(_DEBUG_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[DEBUG]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "DEBUG"
    },
    {
     "expr": "sum by(_INFO_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[INFO]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "INFO"
    },
    {
     "expr": "sum by(_ERROR_) (count_over_time({app=\"$app\", namespace=\"$namespace\"} |= `[ERROR]` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "RPC Server Call Success/Error Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by(errored) (count_over_time({app=\"$app\", namespace=\"$namespace\"} | logfmt | __error__=`` | errored!=\"\" [$__range]))",
     "legendFormat": "Error: {{errored}}"
    }
   ]
  },
  {
   "title": "Raw Access Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{component=\"server\", app=\"$app\", namespace=\"$namespace\"} |= `` | logfmt"
    }
   ]
  }
 ]
}