{
 "title": "Control Plane HCP Logs",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "consul" },
   { "name": "app", "query": "consul" },
   { "name": "component", "query": "connect-injector" }
  ]
 },
 "panels": [
  {
   "title": "Connect Injector Function Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `webhooks.serviceintentions` | __error__=`` [$__range])",
     "legendFormat": "webhooks.serviceintentions"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `controller.endpoints` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "controller.endpoints"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `controller.servicedefaults` | __error__=`` [$__range]))",
     "legendFormat": "controller.servicedefaults"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `controller.serviceintentions` | __error__=`` [$__range]))",
     "legendFormat": "controller.serviceintentions"
    }
   ]
  },
  {
   "title": "Log Type Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `TRACE` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "TRACE"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `DEBUG` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "DEBUG"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `INFO` | __error__=`` [$__range]))",
     "legendFormat": "INFO"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `ERROR` | __error__=`` [$__range]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "Connect Injector Function Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `webhooks.serviceintentions` | __error__=`` [$__range])",
     "legendFormat": "webhooks.serviceintentions"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `controller.endpoints` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "controller.endpoints"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `controller.servicedefaults` | __error__=`` [$__range]))",
     "legendFormat": "controller.servicedefaults"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `controller.serviceintentions` | __error__=`` [$__range]))",
     "legendFormat": "controller.serviceintentions"
    }
   ]
  },
  {
   "title": "Log Type Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `TRACE` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "TRACE"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `DEBUG` | logfmt | __error__=`` [$__range]))",
     "legendFormat": "DEBUG"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `INFO` | __error__=`` [$__range]))",
     "legendFormat": "INFO"
    },
    {
     "expr": "sum(count_over_time({app=\"$app\", namespace=\"$namespace\", component=\"$component\"} |= `ERROR` | __error__=`` [$__range]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "Raw Access Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{component=\"$component\", app=\"$app\", namespace=\"$namespace\"} |= ``",
     "maxLines": 200
    }
   ]
  }
 ]
}