# Do not use this configuration in production.
# It is for demonstration purposes only.

loki:
  enabled: true
  isDefault: true
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"

#promtail:
#  enabled: false
  
promtail:
  enabled: true
  config:
    lokiAddress: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push
  podAnnotations:
    "consul.hashicorp.com/connect-inject": "false"