{
 "title": "Data Plane Logs",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "default" },
   { "name": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  {
   "title": "HTTP Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({container=\"consul-dataplane\", app=\"$app\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(response_code) (count_over_time({container=\"consul-dataplane\", app=\"$app\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "User Agent Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(user_agent) (count_over_time({container=\"consul-dataplane\", app=\"$app\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "HTTP Method Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(method) (count_over_time({container=\"consul-dataplane\", app=\"$app\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Response Code Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by(response_code) (count_over_time({container=\"consul-dataplane\", app=\"$app\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Response Code Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by(user_agent) (count_over_time({container=\"consul-dataplane\", app=\"$app\", namespace=\"$namespace\"} | json | __error__=`` [$__range]))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Raw Access Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{container=\"consul-dataplane\", app=\"$app\", namespace=\"$namespace\"} |= `` | json"
    }
   ]
  }
 ]
}