---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: frontend
  namespace: default
spec:
  destination:
    name: frontend
  sources:
    # Allow traffic from nginx to frontend
    - name: nginx
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: public-api
  namespace: default
spec:
  destination:
    name: public-api
  sources:
    # Allow traffic from nginx to public-api
    - name: nginx
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product-api
  namespace: default
spec:
  destination:
    name: product-api
# Allow traffic from public-api to product-api
  sources:
    - name: public-api
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product-api-db
  namespace: default
spec:
  destination:
    name: product-api-db
  # Allow traffic from product-api to product-api-db
  sources:
    - name: product-api
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
  namespace: default
spec:
  destination:
    name: payments
  # Allow traffic from public-api to payments
  sources:
    - name: public-api
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: nginx
  namespace: default
spec:
  destination:
    name: nginx
  sources:
    # Allow traffic from api-gateway to nginx
    - name: api-gateway
      action: allow
    # Allow traffic from traffic-generator to nginx
    - name: traffic
      action: allow